name: build & test docker

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v3

        -   name: Set up Docker
            uses: docker/setup-buildx-action@v3

        -   name: Build Docker image
            run: docker build -t flask-ci-app .

        -   name: Run container in background
            run: |
                docker run -d -p 5000:5000 --name testapp flask-ci-app
                sleep 5

        -   name: Test HTTP endpoint
            run: |
                curl -f http://localhost:5000/janusz