name: build & test docker

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: krystianostr
        password: ${{ secrets.GHCR_PAT }}

    - name: Build Docker image
      run: docker build -t ghcr.io/krystianostr/flask-pytest-azure-cicd:latest .

    - name: Push image to GHCR
      run: docker push ghcr.io/krystianostr/flask-pytest-azure-cicd:latest

    - name: Run container in background
      run: |
        docker run -d -p 80:80 --name testapp ghcr.io/krystianostr/flask-docker-azure-cicd:latest
        sleep 10
        docker ps -a
        docker logs testapp
    
    - name: Test HTTP /
      run: curl -f http://localhost:80/ | grep "Hello, DevOps!"
    