name: build & test docker

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v3

        -   name: Set up Docker
            uses: docker/setup-buildx-action@v3
            with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.GHCR_PAT}}

        -   name: Build Docker image
            run: docker build -t ghcr.io/krystianostr/flask-ci-app:latest .

        -   name: Push image to GHCR
            run: docker push ghcr.io/krystianostr/flask-ci-app:latest

        -   name: Run container in background
            run: |
              docker run -d -p 5000:5000 --name testapp flask-ci-app
              sleep 10
              docker ps -a
              docker logs testapp
          

        -   name: Test HTTP /
            run: |
                  curl -f http://localhost:5000/ | grep "Hello, DevOps!"
              
        -   name: Test HTTP /janusz
            run: |
                  curl -f http://localhost:5000/janusz | grep "Hello, Janusz!"